# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
#
# Vatu:    PHP Compatibility
# Version: 0.1.0
# Author:  Michael Bragg <mike@vatu.dev>

name: 'PHP Compatibility'
description: ''
author: 'Vatu <hello@vatu.dev>'

inputs:

  php-version:
    description: "Version of PHP to test against. Eg, `8.2`"
    required: true

runs:
  using: 'composite'

  steps:

    - name: 'Install PHP Parallel Lint'
      shell: bash
      run: |
        composer --working-dir=tools/php-compat require --dev php-parallel-lint/php-parallel-lint

    - name: "Debug"
      shell: bash
      run: |
        php --version
        composer --version
        ./tools/php-compat/vendor/bin/parallel-lint --version
