# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
#
# Vatu:    PHP Compatibility
# Version: 0.1.0
# Author:  Michael Bragg <mike@vatu.dev>

name: 'PHP Compatibility'

on:
  workflow_call:

    inputs:

      runs-on:
        description: "Runner to be used by the parent workflow."
        required: false
        type: string
        default: 'ubuntu-latest'

      branch:
        description: "Choose the branch to run this test against."
        required: false
        type: string
        default: 'main'

      php-version:
        description: "Version of PHP to test against. Eg, `['8.2', '8.3']`"
        required: false
        type: string
        default: "['8.0', '8.1', '8.2', '8.3']"

jobs:

  test:

    runs-on: ${{ inputs.runs-on }}

    strategy:
      fail-fast: true
      matrix:
        php-version: ${{ fromJson(inputs.php-version) }}

    name: "PHP ${{ matrix.php-version }}"
    timeout-minutes: 15

    steps:

      - name: "Checks out the repository."
        uses: "actions/checkout@v3.5.0"
        with:
          ref: ${{ inputs.branch }}

      - name: "Debug"
        run: |
          echo "PHP ${{ matrix.php-version }}"
