---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
#
# Vatu:    PHP Compatibility
# Author:  Michael Bragg <mike@vatu.dev>

name: 'PHP Compatibility'
description: ''
author: 'Vatu <hello@vatu.dev>'

inputs:

  php-version:
    description: "Version of PHP to test against. Eg, `8.2`"
    required: true

runs:
  using: 'composite'

  steps:

    - name: 'Install PHP Compatibility'
      shell: bash
      run: |
        composer --working-dir=tools/php-compat require --dev squizlabs/php_codesniffer:"*" --quiet
        composer --working-dir=tools/php-compat config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true --quiet
        composer --working-dir=tools/php-compat require --dev dealerdirect/phpcodesniffer-composer-installer --quiet
        composer --working-dir=tools/php-compat require --dev phpcsstandards/phpcsdevtools:^1.0 --quiet
        composer --working-dir=tools/php-compat require phpcompatibility/php-compatibility:"dev-develop as 9.99.99" --quiet
        composer --working-dir=tools/php-compat require phpcompatibility/phpcompatibility-wp:^2.0 --quiet

    - name: 'Download PHPCompatibility config.'
      shell: bash
      run: |
          curl -s -L https://raw.githubusercontent.com/vatu-team/php-compatibility-config/latest/phpcompatibility.dist.xml --output phpcompatibility.dist.xml --fail
      continue-on-error: false

    - name: 'Setup PHP Code Sniffer Config.'
      shell: bash
      run: |
        ./tools/php-compat/vendor/bin/phpcs --config-set ignore_warnings_on_exit 1 --quiet

    - name: 'Debug.'
      shell: bash
      run: |
        php --version
        composer --version
        ./tools/php-compat/vendor/bin/phpcs --version
        ./tools/php-compat/vendor/bin/phpcs -i

    - name: 'Run PHP Compatibility Tests.'
      shell: bash
      run: |
        ./tools/php-compat/vendor/bin/phpcs -p -s --colors --standard=phpcompatibility.dist.xml --extensions=php --runtime-set testVersion ${{ matrix.php-version }} ./
